name: Automate Docker Image Build & Push to Quay.io Registry CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - closed
      - labeled
      - unlabeled
      - edited

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ID }}
          password: ${{ secrets.QUAY_PW }}
      -
        name: Find Changed/Added Files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      -
        name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24
        with:
          files: |
            containers/Dockerfile
      -
        name: Get current date # get the date of the build
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      -
        name: Building & Pushing Docker Image
        run: |
          docker build . --tag quay.io/$QUAY_NAMESPACE/appeng-backstage:ci_${{ steps.date.outputs.date }}
          docker push quay.io/$QUAY_NAMESPACE/appeng-backstage:ci_${{ steps.date.outputs.date }}